$choice command
pajbot/pajbot2-discord pull request #81
Opened 2021-07-08 12:34 UTC by Nhlest

# Description

Adds $choice command that returns a randomly chosen word from the list of arguments given.

Who asked: me :)
Issue: N/A

2021-07-10 11:35 UTC, pajlada commented
Looks good, will test and make a final review tomorrow 👌

2021-07-17 16:20 UTC, Nhlest commented
┌[ ◔ ͜ ʖ ◔ ]┐

2021-07-18 11:24 UTC, pajlada requested changes

2021-07-18 11:24 UTC, pajlada commented on internal/commands/choice/choice.go
> +	response := fmt.Sprintf("%s, %s", m.Author.Mention(), parts[rand.Intn(len(parts))])
When figuring out which part has been chosen, you need to ensure the list isn't empty.

Make sure the command doesn't crash with 0 arguments (i.e. `$choice`) and make sure the command doesn't run when only 1 argument is specified (i.e. `$choice foo`).

2021-07-18 11:24 UTC, pajlada commented on internal/commands/choice/choice.go
> +	s.ChannelMessageSend(m.ChannelID, response)
Make sure we trim out mentions here. You should not be able to do `$choice @everyone @everyone` or `$choice @pajlada @pajlada`

2021-07-18 13:38 UTC, pajlada commented
@Nhlest I think it's best to use https://pkg.go.dev/github.com/bwmarrin/discordgo#Session.ChannelMessageSendComplex to remove mentions instead, you'll need to make sure the `AllowedMentions` parameter https://pkg.go.dev/github.com/bwmarrin/discordgo#MessageAllowedMentions doesn't allow any mentions. Once you've switched to it, I can try it out

2021-07-18 14:08 UTC, Nhlest commented
@pajlada this way if user will try to use $choice word word2 word3 @mention word4 command will misfire 1/5 of the time. Seems like a strange behavior to have in my opinion.

2021-07-31 10:24 UTC, pajlada approved these changes

2021-07-31 10:27 UTC, pajlada commented
Works for me
![image](https://user-images.githubusercontent.com/962989/127736934-53409fb9-1317-476c-810a-6d9ecaca45e4.png)

Known issues:
 - Commands currently give empty values as part of `parts`
so it could be `["a", "b", " ", " ", "c"]` - this is not a bug of this module, rather of the command matcher.
 - Disabling mentions also means that the person running the command misses the mention. This could be remediated later by using the reply functionality. Not necessary for this PR though

2021-07-31 10:29 UTC, merged